---
title: "Phase II"
output: html_notebook
---

# Load Libraries 
```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
```

# Candidate Bank Analysis
## Load Phase II data
```{r}
complete_phase_2 <- read.csv("phase_2_data.csv")
complete_phase_2
```

## Labeling Items with Inclusion Criteria
```{r}
k_post <- complete_phase_2 %>%
  filter(!is.na(q1_post) & (q1_post >= 3 & q2_post >= 3 & q3_post == "Y" & q4_post == "Y")) %>% 
  mutate(label = "in")

k_pre <- complete_phase_2 %>%
  filter(is.na(q1_post) & (q1_pre >= 3 & q2_pre >= 3 & q3_pre == "Y" & q4_pre == "Y")) %>% 
  mutate(label = "in")

r_post <- complete_phase_2 %>%
  filter(!is.na(q1_post) & (q1_post < 3 | q2_post < 3 | q3_post != "Y" | q4_post != "Y")) %>% 
  mutate(label = "out")

r_pre <- complete_phase_2 %>%
  filter(is.na(q1_post) & (q1_pre < 3 | q2_pre < 3 | q3_pre != "Y" | q4_pre != "Y")) %>% 
  mutate(label = "out")

combined_df_with_label <- bind_rows(k_post, k_pre, r_post, r_pre)
combined_df_with_label
```
## Final Bank and Average Relevance and Clarity Ratings
```{r}
final_bank <- combined_df_with_label %>% 
  filter(label == "in")
final_bank

temp_avg_flagged_q1 <- final_bank %>%
  filter(!is.na(q1_post)) %>%
  summarise(sum = sum(q1_post)) %>%
  pull(sum)

temp_avg_unflagged_q1 <- final_bank %>%
  filter(is.na(q1_post)) %>% 
  summarise(sum=sum(q1_pre)) %>%
  pull(sum)

temp_avg_flagged_q2 <- final_bank %>%
  filter(!is.na(q2_post)) %>%
  summarise(sum = sum(q2_post)) %>%
  pull(sum)

temp_avg_unflagged_q2 <- final_bank %>%
  filter(is.na(q2_post)) %>% 
  summarise(sum=sum(q2_pre)) %>%
  pull(sum)

ave_q1 <- (temp_avg_flagged_q1 + temp_avg_unflagged_q1) / nrow(final_bank)
ave_q2 <- (temp_avg_flagged_q2 + temp_avg_unflagged_q2) / nrow(final_bank)
ave_q1
ave_q2
```
## Final Bank across (chart type, task) Combinations
```{r}
chart_type_task_results <- final_bank %>%
  mutate(combo = paste(chart_type, task, sep = "-")) %>%
  count(combo)
chart_type_task_results
#write.csv(chart_type_task_results, "chart_type_task_results.csv", row.names = FALSE)
```


## Confusion Matrix for Stage III Performance
```{r}
number_k <- complete_phase_2 %>%
  filter(is.na(q1_post) & (q1_pre >= 3 & q2_pre >= 3 & q3_pre == "Y" & q4_pre == "Y"))
number_k

number_kk <- complete_phase_2 %>%
  filter(!is.na(q1_post) & (q1_post >= 3 & q2_post >= 3 & q3_post == "Y" & q4_post == "Y")) %>% 
  filter(q1_pre >= 3 & q2_pre >= 3 & q3_pre == "Y" & q4_pre == "Y")
number_kk

number_rk <- complete_phase_2 %>%
  filter(!is.na(q1_post) & (q1_post >= 3 & q2_post >= 3 & q3_post == "Y" & q4_post == "Y")) %>% 
  filter(q1_pre < 3 | q2_pre < 3 | q3_pre != "Y" | q4_pre != "Y")
number_rk

number_r <- complete_phase_2 %>%
  filter(is.na(q1_post) & (q1_pre < 3 | q2_pre < 3 | q3_pre != "Y" | q4_pre != "Y")) 
number_r

number_rr <- complete_phase_2 %>%
  filter(!is.na(q1_post) & (q1_post < 3 | q2_post < 3 | q3_post != "Y" | q4_post != "Y")) %>% 
  filter(q1_pre < 3 | q2_pre < 3 | q3_pre != "Y" | q4_pre != "Y")
number_rr

number_kr <- complete_phase_2 %>%
  filter(!is.na(q1_post) & (q1_post < 3 | q2_post < 3 | q3_post != "Y" | q4_post != "Y")) %>% 
  filter(q1_pre >= 3 & q2_pre >= 3 & q3_pre == "Y" & q4_pre == "Y")
number_kr
```


