context:
  [
    health,
    population and demography,
    energy and environment,
    weather and climate,
    food and agriculture,
    economy,
    politics,
    education,
    innovation,
  ]

gpt_model: "gpt-4-1106-preview"

prompt:
  system_text: |
    You generate datasets and make data visualizations based on the datasets and the user's specific requirements. 
    You use R programming language and, unless specified, only use libraries including "ggplot2", "tidyverse", and "dplyr" to generate the datasets and data visualizations. 
    You should store two things:
      (1) the realized dataset in a txt file under the folder "generated_dataset_session_1".
      (2) the image of the data visualization under the folder "generated_vis_session_1".

  user_text_1: |
    I will give you a context and a chart type of data visualization. I want you to use R programming language to make a synthetic dataset in the given context and a data visualization of the specified chart type based on the synthetic dataset.
    Here is the context: {context}. 
    Here is the type of data visualization: {chart_type}. 
    The values in the synthetic datasets must have meaningful names in the given context. 
    All values in the dataset must be whole numbers.
    Make sure to generate a dataset that is well suited for the chart type.
    Next, I will give you additional requirements for the visualization and the dataset.

  assistant_text_1: |
    I have received the context and the type of data visualization. 
    Please provide additional requirements for the visualization and the dataset.

  user_text_2: |
    The data visualization must be well-designed with the following requirements:
      (1) There should be a title for the visualization. Display the title at the top. Do not overlay the title on other components of the visualization.
      (2) Do not overcrowd color legends or axes with labels. 
      (3) Leave enough margins around the visualization so that all labels are displayed fully.
      (4) All data points in the dataset must be displayed on the visualization.
      (5) Do not use month as a type of value in the dataset.
    For {chart_type}, {chart_type_specific_requirements}
    Next, I will give you more instructions on how to format your response and how to store the outputs of the R code.

  assistant_text_2: |
    I have received additional requirements for the visualization and the dataset.
    Please provide further instructions on how to format my response and how to store the outputs of the R code.

  user_text_3: |
    In your response, I want you to give me the R code that generated the dataset and the data visualization. 
    In your response, do not indent the code block, load all necessary R libraries at the start of the code. In addition, you must start the first line of the R code in a new line after a line with "```R" and have a new line with "```" after the last line of R code.
    In the R code, you must do the following two things to store the output:
      (1) under the folder "generated_dataset_session_1", save the realized dataset as a txt file. The name of this file should be "{chart_type}-{context}.txt". Make sure to connect every single word in the file name with an underscore. 
      (2) under the folder "generated_vis_session_1", save the image you created as a png. The file name of the image follows this format: "{chart_type}-{context}.png". Make sure to connect every single word with an underscore. After you save the image, please do not show me the image. Just save it.

chart_type:
  line chart: |
    create a dataset that has only one type of numerical value. The number of data points in the dataset must be no more than 20. The data points in the dataset must have {trend}. There should be only one line on the visualization.
  bar chart: |
    create a dataset that has only one type of numerical value. The number of data points in the dataset must be no more than 20. All bars should share the same color.
  stacked bar chart: |
    create a dataset that has only one type of numerical value and where the number of segments in each bar do not exceed 5. The number of bars must be no more than 8.
  100 percent stacked bar chart: |
    create a dataset that has only one type of numerical value that is percentage where every value must be positive. All segments of a bar must add up to exactly 100 percent. You must include "scale_y_continuous(labels = percent_format(), breaks = seq(0, 1, 0.2))" in your code
  pie chart: |
    create a dataset that has only one type of numerical value that is percentage. The dataset must only have positive values. You must use "geom_text()" to label the names of categories on the slices of the pie chart. You must not label the percentages on the pie chart.
  histogram: |
    create a dataset that has only a single column with one type of numerical value (not temporal or categorical). The distribution of the data must be {skew}. The number of bins on the x-axis must be between 3 and 20. You must be specific about what the frequency or count is for on the y-axis label (e.g., number of people).
  scatterplot: |
    create a dataset that has two types of numerical values (not temporal) and use the x and y axes to encode them. The two types of values on the x and y axes must have {correlation}. The number of data points in the dataset should be between 20 and 50. All dots should share the same color. Do not mention the correlation in the title of the visualization.
  area chart: |
    create a dataset that has only one type of numerical value. The dataset must only have positive values. The number of data points in the dataset must be no more than 20. The data points in the dataset must have {trend}. There should be only one line on the visualization, and the area below the line should be filled in with a color.
  stacked area chart: |
    create a dataset that has only one type of numerical value for each group. The dataset must only have positive values. Each group must be displayed on top of each other. All groups must have the same number of data points, and the number of data points in each group must be no more than 20.
  bubble chart: |
    create a dataset that has three types of numerical values (not temporal) and use the x and y axes to encode two of them and use the size of the bubble to encode the other. The two types of values on the x and y axes must have {correlation}. Use a color legend to distinguish the bubbles. The number of data points in the dataset should be between 5 and 8. The bubbles must not have too much overlap.
  choropleth map: |
    create a dataset that has the lowercased full names of 50 U.S. states and 'district of columbia' in one column and numerical values in another column. Make sure each state is associated with exactly one numerical value. You must label the abbreviation of each state on the map. You must use the "choroplethr" R library and "state_choropleth" function to create the visualization.
  tree map: |
    create a dataset that has two columns named 'Category' and 'Subcategory' and only one type of numerical value in the third column that is percentage. Each category must have two or three subcategories in the dataset. The sum of all values in the dataset must be exactly 100 percent. No single value should be more than 80 percent. The number of data points in the dataset must not exceed 15. You must use the "treemapify" R library to create the visualization. You must set "geom_treemap("colour = "black")" and set "grow=FALSE" in "geom_treemap_text()". The color legend for 'Category' must be displayed on the right side of the tree map. You must set "subgroup = Category" to ensure that the rectangles for all subcategories within a category are adjacent on the tree map.
  # scatterplot with outlier: |
  #   create a dataset that has two types of numerical values (not temporal) and use the x and y axes to encode them. The two types of values on the x and y axes must have {correlation}. The number of data points in the dataset should be between 20 and 50. All dots should share the same color. There must be an outlier data point in the dataset. Do not use a different color for the outlier. Do not include the word "outlier" in the title of the visualization.
  # scatterplot with cluster: |
  #   create a dataset that has two types of numerical values (not temporal) and use the x and y axes to encode them. The two types of values on the x and y axes must have {correlation}. The number of data points in the dataset should be between 20 and 50. All dots should share the same color. There must be a visible cluster of 10 to 15 data points close together in the scatterplot. All points in the cluster must be no more than 2% away from the cluster center. The cluster must have the same color as all the other points in the dataset. Do not include the word "cluster" in the title of the visualization.
  # bubble chart with outlier: |
  #   create a dataset that has three types of numerical values (not temporal) and use the x and y axes to encode two of them and use the size of the bubble to encode the other. The two types of values on the x and y axes must have {correlation}. There must be an outlier data point in the dataset. Use a color legend to distinguish the bubbles. All bubbles must have different colors. The number of data points in the dataset should be between 5 and 8. Do not use "outlier" in the name of the outlier data point. Do not include the word "outlier" in the title of the visualization.
  # bubble chart with cluster: |
  #   create a dataset that has three types of numerical values (not temporal) and use the x and y axes to encode two of them and use the size of the bubble to encode the other. The two types of values on the x and y axes must have {correlation}. Use a color legend to distinguish the bubbles. The number of data points in the dataset should be between 5 and 10. There must be a visible cluster of 3 or 4 data points close together on the x-y plane in the bubble chart. All bubbles in the cluster must be no more than 2% away from the cluster center. Do not use "cluster" as the names of bubbles on the color legend. Do not include the word "cluster" in the title of the visualization.
