"use client";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/app/components/ui/card';
import { BarChart, Code, Github, FileText, ChevronRight, Zap, Lightbulb, Target, Users, Grid } from 'lucide-react';

const FeatureCard = ({ icon: Icon, title, description }) => (
  <div className="group p-6 rounded-xl border bg-white hover:shadow-lg transition-all duration-300">
    <div className="flex items-center gap-4 mb-3">
      <div className="p-3 rounded-lg bg-cyan-50 text-cyan-600 group-hover:bg-cyan-100 transition-colors">
        <Icon className="h-6 w-6" />
      </div>
      <h3 className="font-semibold text-lg">{title}</h3>
    </div>
    <p className="text-gray-600">{description}</p>
  </div>
);

const StatCard = ({ value, label, icon: Icon }) => (
  <div className="flex flex-col items-center p-6 bg-gradient-to-br from-cyan-50 to-white rounded-xl border hover:shadow-md transition-all duration-300">
    <Icon className="h-8 w-8 text-cyan-600 mb-2" />
    <span className="text-2xl font-bold text-gray-900">{value}</span>
    <span className="text-sm text-gray-600">{label}</span>
  </div>
);

const AboutPage = () => {
  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <div className="bg-gradient-to-b from-cyan-50 to-white rounded-2xl">
        <div className="max-w-6xl mx-auto px-4 py-20 text-center">
          <h1 className="text-5xl font-bold mb-6">
            VILA Visualization Item Bank
          </h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto mb-8">
            Exploring the future of visualization education through AI-generated examples
          </p>
          <div className="flex flex-wrap gap-4 justify-center">
            <button 
              onClick={() => window.location.href = '/matrix'}
              className="bg-cyan-600 text-white px-6 py-3 rounded-lg hover:bg-cyan-700 transition-all duration-200 flex items-center gap-2"
            >
              <Grid className="h-5 w-5" />
              View Matrix
            </button>
            <button 
              onClick={() => window.location.href = '/gallery'}
              className="bg-white text-cyan-600 px-6 py-3 rounded-lg border-2 border-cyan-600 hover:bg-cyan-50 transition-all duration-200 flex items-center gap-2"
            >
              <BarChart className="h-5 w-5" />
              Explore Bank
            </button>
            <a 
              href="https://mucollective.northwestern.edu/files/2024-vila.pdf" 
              target="_blank"
              rel="noopener noreferrer"
              className="bg-white text-gray-600 px-6 py-3 rounded-lg border-2 border-gray-300 hover:bg-gray-50 transition-all duration-200 flex items-center gap-2"
            >
              <FileText className="h-5 w-5" />
              Read Paper
            </a>
          </div>
        </div>
      </div>

      {/* Project Overview Section */}
      <div className="bg-white py-16">
        <div className="max-w-6xl mx-auto px-4">
          <div className="bg-gradient-to-r from-cyan-50 to-white p-8 rounded-2xl shadow-sm">
            <h2 className="text-3xl font-bold mb-6">Project Overview</h2>
            <p className="text-lg text-gray-600 leading-relaxed">
              The VILA (Visualization Items Generated by Large LAnguage Models) project investigates the potential for large language models to automate the generation of multiple-choice visualization items. Our collection showcases curated examples across different chart types and analytical tasks, helping users understand how different visualization techniques can be applied effectively in various contexts.
            </p>
          </div>
        </div>
      </div>

      {/* Stats Section */}
      <div className="max-w-6xl mx-auto px-4 py-12">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
          <StatCard icon={BarChart} value="1,100+" label="Visualizations" />
          <StatCard icon={Code} value="12" label="Chart Types" />
          <StatCard icon={Target} value="13" label="Visualization Tasks" />
          <StatCard icon={Lightbulb} value="9" label="Different Contexts" />
        </div>
      </div>

      {/* Features Grid */}
      <div className="max-w-6xl mx-auto px-4 py-12">
        <h2 className="text-3xl font-bold text-center mb-12">Key Features</h2>
        <div className="grid md:grid-cols-2 gap-6">
          <FeatureCard
            icon={Zap}
            title="AI-Powered Generation"
            description="Using state-of-the-art large language models to create diverse visualization items at scale."
          />
          <FeatureCard
            icon={Target}
            title="Comprehensive Coverage"
            description="Spanning multiple contexts from economy to healthcare, with visualization tasks covering all levels of Bloom's taxonomy."
          />
          <FeatureCard
            icon={Users}
            title="Expert Validated"
            description="Each item evaluated by visualization experts for relevance, clarity, and correctness."
          />
          <FeatureCard
            icon={Lightbulb}
            title="Educational Impact"
            description="Supporting visualization research education through carefully curated materials."
          />
        </div>
      </div>

      {/* Applications Section */}
      <div className="bg-gradient-to-b from-white to-cyan-50 py-12 rounded-2xl">
        <div className="max-w-6xl mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-12">Applications</h2>
          <div className="grid md:grid-cols-3 gap-8">
            {[
              {
                title: "Research",
                description: "Support for visualization literacy studies, adaptive testing, and visualization question-answering systems.",
                items: ["Literacy Studies", "Adaptive Testing", "VQA Systems"]
              },
              {
                title: "Education",
                description: "Resources for teaching data visualization courses and creating effective assessments.",
                items: ["Course Materials", "Student Exercises", "Assessments"]
              },
              {
                title: "Practice",
                description: "Reference materials for understanding effective visualization techniques.",
                items: ["Best Practices", "Technique Examples", "Design Patterns"]
              }
            ].map((app, index) => (
              <Card key={index} className="hover:shadow-lg transition-shadow duration-300">
                <CardHeader>
                  <CardTitle>{app.title}</CardTitle>
                  <CardDescription>{app.description}</CardDescription>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2">
                    {app.items.map((item, i) => (
                      <li key={i} className="flex items-center gap-2 text-gray-600">
                        <ChevronRight className="h-4 w-4 text-cyan-600" />
                        {item}
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </div>

      {/* Credits Section */}
      <div className="max-w-6xl mx-auto px-4 py-12">
        <Card>
          <CardHeader>
            <CardTitle>Credits</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <h3 className="font-semibold mb-3">Research Team</h3>
                <p className="text-gray-600">
                  Yuan Cui, Lily W. Ge, Yiren Ding, Lane Harrison, Fumeng Yang, and Matthew Kay
                </p>
              </div>
              <div>
                <h3 className="font-semibold mb-3">Developers</h3>
                <p className="text-gray-600">
                  Jovy Zhou, 
                  Harry Guan,
                  <a href="https://digital-flaneur.github.io/" 
                    target="_blank" 
                    rel="noopener noreferrer">,
                    className="flex items-center gap-2 text-cyan-600 hover:text-cyan-700 transition-colors"
                  >
                    Charles Cui
                  </a>
                </p>
              </div>
              <div className="md:col-span-2">
                <p className="text-gray-600">
                  This work was supported by grants from the National Science Foundation and the Northwestern Institute on Complex Systems.
                </p>
                <div className="flex items-center gap-2 mt-4">
                  <a 
                    href="https://osf.io/ysrhq/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center gap-2 text-cyan-600 hover:text-cyan-700 transition-colors"
                  >
                    <Github className="h-5 w-5" />
                    View Project on OSF
                  </a>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default AboutPage;
