---
title: "Data Cleaning and Anonymization for Convergent Validity of VILA-VLAT"
output: html_notebook
---

# Load libraries 
```{r}
library(dplyr)
library(tidyverse)
```

# Read group 1 participant ID data
```{r}
prolific_vilavlat2_pid <- read.csv("data/demo_gpt_2nd.csv") %>% 
  rename(participant = Participant.id) %>% 
  filter(Status == "AWAITING REVIEW")
```

# Read group 2 participant ID data
```{r}
prolific_vlat2_pid <- read.csv("data/demo_vlat_2nd.csv") %>% 
  rename(participant = Participant.id) %>% 
  filter(Status == "AWAITING REVIEW")
```

# Read group 1 data
```{r}
df_vlat_1_df <- read.csv("data/vlat_1st.csv") %>% 
  filter(participantId %in% prolific_vilavlat2_pid$participant)

df_vila_vlat_2_df <- read.csv("data/gptvlat_2nd.csv") %>%
  filter(participantId %in% prolific_vilavlat2_pid$participant) %>% 
  #remove two items not in the final bank that were mistakenly administered due to an implementation error 
  filter(trialId != "choropleth_map-locate_value-health") %>% 
  filter(trialId != "bubble_chart-make_comparisons-politics")
```

# Read group 2 data
```{r}
df_vila_vlat_1_df <- read.csv("data/gptvlat_1st.csv") %>% 
  filter(participantId %in% prolific_vlat2_pid$participant) %>% 
  #remove two items not in the final bank that were mistakenly administered due to an implementation error 
  filter(trialId != "choropleth_map-locate_value-health") %>% 
  filter(trialId != "bubble_chart-make_comparisons-politics")

df_vlat_2_df <- read.csv("data/vlat_2nd.csv") %>%
  filter(participantId %in% df_vila_vlat_1_df$participant)
```

# Bind corresponding tests
```{r}
df_vlat_combined <- rbind(df_vlat_1_df, df_vlat_2_df)
df_vila_vlat_combined <- rbind(df_vila_vlat_2_df, df_vila_vlat_1_df)

# Format the correct answer column properly
df_vila_vlat_combined <- df_vila_vlat_combined %>% 
  mutate(correctAnswer =  ifelse(!startsWith(trialId,"at"), substring(correctAnswer, 5), correctAnswer)) 
```

# Select relevant columns
```{r}
df_vlat <- df_vlat_combined %>% 
  select(participantId, trialId, answer, correctAnswer)

df_vila_vlat <- df_vila_vlat_combined %>% 
  select(participantId, trialId, answer, correctAnswer)
```


# Attention checks: filter out participants who didn't pass attention checks
```{r}
attention_checks_vlat <- df_vlat %>% 
  filter(startsWith(trialId, "at")) %>% 
  filter(answer != correctAnswer) %>% 
  group_by(participantId) %>% 
  summarise(failed_checks = n()) %>% 
  filter(failed_checks >= 2) 

attention_checks_vila_vlat <- df_vila_vlat %>% 
  filter(startsWith(trialId, "at")) %>% 
  filter(answer != correctAnswer) %>% 
  group_by(participantId) %>% 
  summarise(failed_checks = n()) %>% 
  filter(failed_checks >= 2) 

df_vlat_items <- df_vlat %>% 
  filter(!participantId %in% attention_checks_vlat$participantId) %>% 
  filter(!participantId %in% attention_checks_vila_vlat$participantId) %>% 
  filter(startsWith(trialId, "q"))

df_vila_vlat_items <- df_gpt_vlat %>% 
  filter(!participantId %in% attention_checks_vila_vlat$participantId) %>% 
  filter(!participantId %in% attention_checks_vlat$participantId) %>% 
  filter(trialId != "consent") %>% 
  filter(!startsWith(trialId, "at"))
```

# Anonymization
```{r}
set.seed(2024)
unique_count <- length(unique(df_vlat_items$participantId))

df_pid <- data.frame(participantId = unique(df_vlat_items$participantId), pid = paste0("p", sample(seq(1, unique_count), size = unique_count, replace = FALSE)))

vlat_df <- df_vlat_items %>%
  left_join(df_pid, by = c("participantId" = "participantId")) %>% 
  select(-participantId)
vlat_df
write.csv(vlat_df, "data/anonymized_data_on_87_VLAT.csv", row.names = FALSE)

vilavlat_df <- df_vila_vlat_items %>% 
  left_join(df_pid, by = c("participantId" = "participantId")) %>% 
  select(-participantId) 
vilavlat_df
write.csv(gptvlat_df, "data/anonymized_data_on_87_VILAVLAT.csv", row.names = FALSE)
```
